### ISSUE TITLE
How do I get Blender Retarget to work in Blender 2.81 ?

### ISSUE THREAD

**Issue by Mehdianim** [igelbox/blender-retarget#4]
Hi Sergey,
I like your retarget addon it is super useful. I was not able to get it working with Blender 2.81 and I'm not the best at Scripting, Can you provide any ideas as to why It won't work ?
I used the Zip file to install it from the Addons install menu.
I get a message that it worked :

> Modules Installed () from 'D:\\apps\\Blenderaddons\\blender-retarget-master.zip into 'C:\\Users\\mehdianim\\Appdata\\Roaming\\Blender Foundation\\Blender\\2.81\\Scripts\\addons'

The problem is the Addon doesn't appear in the list of installed addons after refresh.
Also checked that when I select an armature or rig object the retargeter menus don't appear in the object Properties tab like it did in Blender 2.79.

Any help would be greatly appreciated !

**Comment by igelbox** [comment]
Ouch.
@Mehdianim thank you for filing this. I'd like to consider this as a bug, coz, 2.8 is a mainline now.

As for the installation approach - I don't believe installing from `-master.zip` would work. That's why I publish Blender-compatible ZIPs at https://github.com/igelbox/blender-retarget/releases.

Anyway, this needs to be fixed, so I'm just started working on this and now struggling with auto-updating (refreshing) 3D view after button clicks - https://github.com/igelbox/blender-retarget/compare/issues/4/support-2.81.

**Comment by igelbox** [comment]
Argh. Due to `depsgraph` (since 2.80), Blender isn't refreshing driver variables if they're bound to the same object.
I can envision a couple of ways to go:
- use `Scripted Expression` as the driver type, **but**, this will require allowing script execution for every blend-file which isn't secure.
- rewrite the whole approach to use bone constraints rather than drivers, **but**, I'm not sure this will work at all.

**Comment by Mehdianim** [comment]
Aw man. 
If you set up the constraints to drive the target rig then bake the keys down to the controls and remove the constraints shouldn't that do the trick ?
At the very least, if you use the FK controls, then you can use rotation constraints on everything except the pelvis which would need rotation and location with offset.
This means, if you were animating with Ik you would need to snap the FK limbs to the IK before running the retarget, but it shouldn't be too painful.
it could even compare the source and target pelvises height from the ground to determine size difference and apply that factor to the location values on the target pelvis.
actually, when you have both characters in T pose, maybe it could do that with the IK limbs as well ? to retarget IK directly ? It would not be perfect but would still save a lot of time in my opinion...
Just some random ideas, I have no idea how to actually execute this in Blender. I wish I could be of more help.

Thanks for the update though. Good luck !

**Comment by igelbox** [comment]
_just found a bit of time for open source_

This addon isn't about baking keys. I'm trying to avoid this approach, coz, it isn't fluent/flexible (just because it would require rebaking stuff every time you making changes).

Sorry, I don't have enough experience with IK, so, I'm struggling to imagine your proposal. I played a lot with bone constraints, but, didn't manage to figure out some useful parameters combination. So, if you could create a working blend-file to show the approach, I will be able to bring the approach into code.

Anyway, I created a fallback (a tricky fix) (see #5). It would be great if you could take a look and tell me if there's something wrong before I merge it and close this ticket.
