### ISSUE TITLE
has it been tested with blender 3.0?

### ISSUE THREAD

**Issue by Gusher** [igelbox/blender-retarget#9]
has it been tested with blender 3.0?

**Comment by Mehdianim** [comment]
I just tried it it seems to work the same. This is the most flexible retargeter I found after trying 7 or 8 other ones.

**Comment by igelbox** [comment]
Well, actually I haven't manually tested this with any versions of Blender for months, thus, we should rely on feedbacks just like Mehdianim left.
Also, if there's (at GitHub) no issue left then we can assume it works well. Otherwise, if you see any issue/bug - feel free to [create a ticket](https://github.com/igelbox/blender-retarget/issues/new) here.

**Comment by igelbox** [comment]
Works well.
Version 3.0.1 (3.0.1 2022-01-26)
